# Generated by Django 2.1.7 on 2019-03-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curtir',
            name='time_id_time',
        ),
        migrations.RemoveField(
            model_name='curtir',
            name='usuario_id_usuario',
        ),
        migrations.DeleteModel(
            name='Curtir',
        ),
    ]
