# Generated by Django 2.1.7 on 2019-03-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0002_auto_20190321_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_id_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptimes.Time')),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptimes.Usuario')),
            ],
        ),
    ]
