# Generated by Django 2.1.7 on 2019-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0003_curtir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='gols_timeA',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gols_timeB',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
