# Generated by Django 2.1.7 on 2019-03-22 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0009_auto_20190322_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 16, 5, 38, 638553)),
        ),
    ]
