# Generated by Django 2.1.7 on 2019-03-25 16:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0011_auto_20190322_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='admin_time',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 16, 10, 44, 587008)),
        ),
    ]
