# Generated by Django 2.1.7 on 2019-04-15 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0014_auto_20190325_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorNaPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField(default=0)),
                ('cartoes_amarelos', models.IntegerField(default=0)),
                ('cartoes_vermelhos', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptimes.Jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptimes.Partida')),
            ],
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 15, 43, 43, 179957)),
        ),
    ]
