# Generated by Django 2.1.7 on 2019-04-15 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0015_auto_20190415_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 15, 44, 17, 211430)),
        ),
    ]
