# Generated by Django 2.1.7 on 2019-04-16 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0016_auto_20190415_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidasEditadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2019, 4, 16, 0, 55, 30, 14619))),
                ('editada', models.IntegerField(default=0)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptimes.Partida')),
            ],
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 0, 55, 30, 13656)),
        ),
    ]
