# Generated by Django 2.1.7 on 2019-04-22 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptimes', '0017_auto_20190416_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadornapartida',
            name='time',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='apptimes.Time'),
        ),
        migrations.AlterField(
            model_name='partidaseditadas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 16, 41, 40, 77774)),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 16, 41, 40, 76768)),
        ),
    ]
